### ISSUE TITLE
ncm2_tern@yarp Job is dead

### ISSUE THREAD

**Issue by jwtcmu9316-zz** [ncm2/ncm2-tern#4]
I have ncm2-tern as part of my [dotfiles](https://github.com/jwtcmu9316/.dotfiles) and I noticed this morning that tern no longer works. I have installed tern via npm globally, I've installed yarp, ncm2, and ncm2-tern, checked to make sure Python was enabled in nvim, confirmed that .tern-config is in my home directory and still I can't get tern to run. Is there an update or something that broke this?

EDIT: I seem to have found the issue. { 'do': 'npm install' } is not firing. Does anyone know why this would be?

**Comment by jwtcmu9316-zz** [comment]
Turns out npm install wasn't running via vim-plug. Whitespace doesn't allow the "do" command to work, for some reason.

**Comment by didILeaveTheStoveOn** [comment]
Hey, did you solve it? Having the same issue I think :sob:

**Comment by mmsilveira** [comment]
I am having the same problem on a new installation with Arch OS.
Someone know how resolve this?

```
[ncm2_tern@yarp] Traceback (most recent call last):
[ncm2_tern@yarp]   File "/home/msilveira/.config/nv...ed/nvim-yarp/pythonx/yarp.py", line 63, in <module>
[ncm2_tern@yarp]     module_obj = importlib.import_module(module)
[ncm2_tern@yarp]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[ncm2_tern@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm2_tern@yarp]   File "/home/msilveira/.config/nv...2-tern/pythonx/ncm2_tern.py", line 188, in <module>
[ncm2_tern@yarp]     source = Source(vim)
[ncm2_tern@yarp]   File "/home/msilveira/.config/nv...2-tern/pythonx/ncm2_tern.py", line 102, in __init__
[ncm2_tern@yarp]     path = nvim.eval(
[ncm2_tern@yarp]   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 295, in eval
[ncm2_tern@yarp]     return self.request('nvim_eval', string, **kwargs)
[ncm2_tern@yarp]   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
[ncm2_tern@yarp]     res = self._session.request(name, *args, **kwargs)
[ncm2_tern@yarp]   File "/usr/lib/python3.8/site-pa...ynvim/msgpack_rpc/session.py", line 104, in request
[ncm2_tern@yarp]     raise self.error_wrapper(err)
[ncm2_tern@yarp] pynvim.api.common.NvimError: Vim:E684: list index out of range: 0
[ncm2_tern@yarp] Job is dead. cmd=['/usr/bin/python...honx/yarp.py', '/tmp/nvimf5GbIz/0', 3, 'ncm2_tern']
```

**Comment by mmsilveira** [comment]
For some reason neovim did not run `{'do': 'npm install'}`.
I installed it manually and work fine. :)
