### ISSUE TITLE
Job is dead. cmd=['/usr/bin/python3', ...... , '/tmp/nvimL912c5/0', 7, 'ncm2_tern']

### ISSUE THREAD

**Issue by moonmoonCL** [ncm2/ncm2-tern#8]
[ncm2_tern@yarp] Traceback (most recent call last):
[ncm2_tern@yarp]   File "/home/moonmoonc/.vim/plugged/nvim-yarp/pythonx/yarp.py", line 63, in <
module>
[ncm2_tern@yarp]     module_obj = importlib.import_module(module)
[ncm2_tern@yarp]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[ncm2_tern@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[ncm2_tern@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

[ncm2_tern@yarp]   File "/home/moonmoonc/.vim/plugged/ncm2-tern/pythonx/ncm2_tern.py", line 188
, in <module>
[ncm2_tern@yarp]     source = Source(vim)
[ncm2_tern@yarp]   File "/home/moonmoonc/.vim/plugged/ncm2-tern/pythonx/ncm2_tern.py", line 104
, in __init__
[ncm2_tern@yarp]     self._tern = Tern(path)
[ncm2_tern@yarp]   File "/home/moonmoonc/.vim/plugged/ncm2-tern/pythonx/ncm2_tern.py", line 44,
 in __init__
[ncm2_tern@yarp]     "stderr: %s\n") % (stdout_output, stderr_output)
[ncm2_tern@yarp] Exception: Did not get expected output starting tern, got the following:
[ncm2_tern@yarp] stdout:
[ncm2_tern@yarp] stderr: Bad JSON in /home/moonmoonc/.tern-config: Unexpected end of JSON input

[ncm2_tern@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/moonmoonc/.vim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvimL912c5/0', 7, 'ncm2_tern']

Someone helps me?

**Comment by Crazy-Ginger** [comment]
I'm getting the same error. 
I've tried installing tern with yay, pip and npm to no avail.
